# Generated by Django 4.1.7 on 2023-03-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
