# Generated by Django 4.1.7 on 2023-03-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_descriptiom_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gassing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gas', models.CharField(choices=[('D', 'Diesel'), ('N', 'Normal gas'), ('E', 'Electricity'), ('P', 'propane')], default='D', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
